version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: strapi-db
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapidb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - strapi-network

  strapi:
    build:
      context: ./strapi-app4
      dockerfile: Dockerfile
    container_name: strapi-app
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapidb
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
      APP_KEYS: key1,key2,key3,key4
      API_TOKEN_SALT: somerandomsalt
      ADMIN_JWT_SECRET: randomjwtsecret
      JWT_SECRET: randomjwtsecret
    ports:
      - "1337:1337"
    networks:
      - strapi-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-network

volumes:
  db_data:

networks:
  strapi-network:
    driver: bridge
